version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATA_DIR=/data
    volumes:
      - database_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  queue:
    build:
      context: ./queue
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CAPACITY=1000
      - CONSUMER_URL=http://webhook-consumer:4000
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Example webhook consumer for testing
  webhook-consumer:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./examples/webhook-consumer.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  database_data:

# Override for development
networks:
  default:
    name: cloudevents-network